;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Status.Concealment.Hidden",DevComment="")
GameplayTagList=(Tag="Status.Concealment.Invisible",DevComment="")
GameplayTagList=(Tag="Status.Concealment.Obscured",DevComment="")
GameplayTagList=(Tag="Status.Concealment.Visible",DevComment="")

