;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/_Project/AI/DataTables/DT_Enemy_motivation.DT_Enemy_motivation
+GameplayTagTableList=/Game/_Project/AI/DataTables/DT_Team_Id.DT_Team_Id
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="State.Affiliation.Enemy",NewTagName="State.Affiliation.Hostile")
+GameplayTagList=(Tag="State",DevComment="")
+GameplayTagList=(Tag="State.Affiliation",DevComment="")
+GameplayTagList=(Tag="State.Affiliation.Friendly",DevComment="")
+GameplayTagList=(Tag="State.Affiliation.Hostile",DevComment="")
+GameplayTagList=(Tag="State.Affiliation.Neutral",DevComment="")
+GameplayTagList=(Tag="State.Affiliation.Player",DevComment="")
+GameplayTagList=(Tag="Status",DevComment="")

